.TH "include/lightmodbus Directory Reference" 3 "Sun Sep 2 2018" "Version 2.0" "liblightmodbus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/lightmodbus Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlightmodbus\&.h\fP"
.br
.RI "Core Modbus functions\&. "
.ti -1c
.RI "file \fBmaster\&.h\fP"
.br
.RI "General Modbus master functions\&. "
.ti -1c
.RI "file \fBparser\&.h\fP"
.br
.RI "Contains the \fBmodbusParser\fP union used during frame creation and parsing\&. "
.ti -1c
.RI "file \fBslave\&.h\fP"
.br
.RI "General Modbus slave functions\&. "
.in -1c
