.TH "include/lightmodbus/master/mpcoils.h" 3 "Sun Sep 2 2018" "Version 2.0" "liblightmodbus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/lightmodbus/master/mpcoils.h \- Master's coil-related parsing functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBModbusError\fP \fBmodbusParseResponse0102\fP (\fBModbusMaster\fP *status, \fBModbusParser\fP *parser, \fBModbusParser\fP *requestParser)"
.br
.RI "Processes responses for requests 01 (read multiple coils) and 02 (read multiple discrete inputs) "
.ti -1c
.RI "\fBModbusError\fP \fBmodbusParseResponse05\fP (\fBModbusMaster\fP *status, \fBModbusParser\fP *parser, \fBModbusParser\fP *requestParser)"
.br
.RI "Processes responses for request 05 (write a single coil) "
.ti -1c
.RI "\fBModbusError\fP \fBmodbusParseResponse15\fP (\fBModbusMaster\fP *status, \fBModbusParser\fP *parser, \fBModbusParser\fP *requestParser)"
.br
.RI "Processes responses for request 15 (write multiple coils) "
.in -1c
.SH "Detailed Description"
.PP 
Master's coil-related parsing functions\&. 


.SH "Function Documentation"
.PP 
.SS "\fBModbusError\fP modbusParseResponse0102 (\fBModbusMaster\fP * status, \fBModbusParser\fP * parser, \fBModbusParser\fP * requestParser)"

.PP
Processes responses for requests 01 (read multiple coils) and 02 (read multiple discrete inputs) 
.PP
\fBNote:\fP
.RS 4
Requires \fCF01M\fP or \fCF02M\fP module (see \fBBuilding liblightmodbus\fP) 
.PP
\fCmodbusParseResponse01\fP and \fCmodbusParseResponse02\fP macros are aliases of this function 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP The master structure to work with 
.br
\fIparser\fP A parser structure containing response data 
.br
\fIrequestParser\fP A parser structure containing request data 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBModbusError\fP error code 
.RE
.PP

.SS "\fBModbusError\fP modbusParseResponse05 (\fBModbusMaster\fP * status, \fBModbusParser\fP * parser, \fBModbusParser\fP * requestParser)"

.PP
Processes responses for request 05 (write a single coil) 
.PP
\fBNote:\fP
.RS 4
Requires \fCF05M\fP module (see \fBBuilding liblightmodbus\fP) 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP The master structure to work with 
.br
\fIparser\fP A parser structure containing response data 
.br
\fIrequestParser\fP A parser structure containing request data 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBModbusError\fP error code 
.RE
.PP

.SS "\fBModbusError\fP modbusParseResponse15 (\fBModbusMaster\fP * status, \fBModbusParser\fP * parser, \fBModbusParser\fP * requestParser)"

.PP
Processes responses for request 15 (write multiple coils) 
.PP
\fBNote:\fP
.RS 4
Requires \fCF15M\fP module (see \fBBuilding liblightmodbus\fP) 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP The master structure to work with 
.br
\fIparser\fP A parser structure containing response data 
.br
\fIrequestParser\fP A parser structure containing request data 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBModbusError\fP error code 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for liblightmodbus from the source code\&.
