.TH "include/lightmodbus/parser.h" 3 "Sun Sep 2 2018" "Version 2.0" "liblightmodbus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/lightmodbus/parser.h \- Contains the \fBmodbusParser\fP union used during frame creation and parsing\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBmodbusParser\fP"
.br
.RI "A big union of structures used for parsing standard Modbus requests and building responses\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef union \fBmodbusParser\fP \fBModbusParser\fP"
.br
.RI "A big union of structures used for parsing standard Modbus requests and building responses\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the \fBmodbusParser\fP union used during frame creation and parsing\&. 


.PP
\fBNote:\fP
.RS 4
This header file is suitable for C++ 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for liblightmodbus from the source code\&.
