.TH "include/lightmodbus/slave Directory Reference" 3 "Sun Sep 2 2018" "Version 2.0" "liblightmodbus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/lightmodbus/slave Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBscoils\&.h\fP"
.br
.RI "Slave's coil-related requests built-in parsing functions\&. "
.ti -1c
.RI "file \fBsregs\&.h\fP"
.br
.RI "Slave's register-related built-in parsing functions\&. "
.in -1c
