.TH "modbusParser" 3 "Sun Sep 2 2018" "Version 2.0" "liblightmodbus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modbusParser \- A big union of structures used for parsing standard Modbus requests and building responses\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((__packed__))"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBframe\fP [256]"
.br
.ti -1c
.RI "\fBbase\fP"
.br
.ti -1c
.RI "\fBexception\fP"
.br
.ti -1c
.RI "\fBrequest0102\fP"
.br
.ti -1c
.RI "\fBresponse0102\fP"
.br
.ti -1c
.RI "\fBrequest0304\fP"
.br
.ti -1c
.RI "\fBresponse0304\fP"
.br
.ti -1c
.RI "\fBrequest05\fP"
.br
.ti -1c
.RI "\fBresponse05\fP"
.br
.ti -1c
.RI "\fBrequest06\fP"
.br
.ti -1c
.RI "\fBresponse06\fP"
.br
.ti -1c
.RI "\fBrequest15\fP"
.br
.ti -1c
.RI "\fBresponse15\fP"
.br
.ti -1c
.RI "\fBrequest16\fP"
.br
.ti -1c
.RI "\fBresponse16\fP"
.br
.ti -1c
.RI "\fBrequest22\fP"
.br
.ti -1c
.RI "\fBresponse22\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A big union of structures used for parsing standard Modbus requests and building responses\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for liblightmodbus from the source code\&.
